# Generated by Django 3.2.5 on 2022-02-16 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genral', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportquery',
            old_name='messgae',
            new_name='message',
        ),
    ]
