# Generated by Django 3.2.5 on 2022-02-06 09:51

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Order Id')),
                ('order_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('service_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Service ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Price')),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('booked', 'booked'), ('cancelled', 'cancelled')], default='pending', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('request_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-request_time'],
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(blank=True, max_length=100, null=True)),
                ('review', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('star_rating', models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Start Rating')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subs_id', models.CharField(blank=True, max_length=20, verbose_name='id')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
