# Generated by Django 3.2.5 on 2022-02-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
