# Generated by Django 3.2.5 on 2022-03-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0013_remove_meeting_rated'),
        ('activity', '0006_ratings_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meet.meeting'),
        ),
    ]
