# Generated by Django 3.2.5 on 2022-03-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_ratings_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='rated',
        ),
    ]
