# Generated by Django 3.2.5 on 2022-01-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscheduletime',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
