# Generated by Django 3.2.5 on 2022-02-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventscheduletime_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventscheduletime',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='timeZone'),
        ),
    ]
