version: "3.9"
services:
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "14000:6379"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis