# Generated by Django 3.2.5 on 2021-12-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=20, verbose_name='payment_id')),
                ('order_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='order_no')),
                ('response', models.JSONField(blank=True, null=True, verbose_name='response')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
