# Generated by Django 3.2.5 on 2022-02-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_refundstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstatus',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='status'),
        ),
    ]
