# Generated by Django 3.2.5 on 2021-08-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Event ID')),
                ('event_name', models.CharField(blank=True, max_length=100, verbose_name='Event Name')),
                ('discription', models.CharField(blank=True, max_length=500, verbose_name='Discription')),
                ('notify_before', models.BooleanField(default=False)),
                ('notify_before_time', models.CharField(blank=True, choices=[('5 Minutes', 5), ('10 Minutes', 10), ('15 Minutes', 15), ('30 Minutes', 30), ('1 Hour', 60)], max_length=50, null=True, verbose_name='Notify Before Time')),
                ('notify_after', models.BooleanField(default=False)),
                ('notify_after_time', models.CharField(blank=True, choices=[('5 Minutes', 5), ('10 Minutes', 10), ('15 Minutes', 15), ('30 Minutes', 30), ('1 Hour', 60)], max_length=50, null=True, verbose_name='Notify After Time')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=30, verbose_name='Day')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=20, verbose_name='payment_id')),
                ('order_no', models.CharField(max_length=20, verbose_name='order_no')),
                ('response', models.JSONField(verbose_name='response')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='EventScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='start time')),
                ('end_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='start time')),
                ('timezone', models.CharField(default='Asia/Kuwait', max_length=255, verbose_name='timeZone')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventschedule')),
            ],
        ),
    ]
