# Generated by Django 3.2.5 on 2022-02-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_auto_20220213_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='add_meeting_btn',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Add Meeting Button'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='join_btn',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Join Button'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='rating_btn',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Rating Button'),
        ),
    ]
