# Generated by Django 3.2.5 on 2022-02-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_auto_20220213_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtypecount',
            name='meet_30',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingtypecount',
            name='meet_45',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingtypecount',
            name='meet_60',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
