# Generated by Django 3.2.5 on 2022-02-13 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_meetingrefundcontainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingrefundcontainer',
            name='expert',
        ),
    ]
