# Generated by Django 3.2.5 on 2022-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0009_meeting_payment_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='refund_enable',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Refund Enable'),
        ),
    ]
