# Generated by Django 3.2.5 on 2022-02-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscheduletime',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
