# Generated by Django 3.2.5 on 2022-02-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_meetingtypecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtypecount',
            name='contained_meet',
        ),
        migrations.AlterField(
            model_name='meetingtypecount',
            name='meet_30',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingtypecount',
            name='meet_45',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingtypecount',
            name='meet_60',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
