# Generated by Django 3.2.5 on 2022-01-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='short_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
