# Generated by Django 3.2.5 on 2022-02-03 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventscheduletime_booked'),
        ('activity', '0003_ratings_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventscheduletime'),
        ),
    ]
