# Generated by Django 3.2.5 on 2022-02-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_order_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('booked', 'booked'), ('cancelled', 'cancelled')], default='pending', max_length=50, null=True),
        ),
    ]
