# Generated by Django 3.2.5 on 2022-02-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20220214_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_no',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RazorPay Order Number'),
        ),
    ]
