# Generated by Django 3.2.5 on 2022-03-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_order_razorpay_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='rated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Rated'),
        ),
    ]
