# Generated by Django 3.2.5 on 2022-02-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220209_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventscheduletime',
            name='end_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='End time'),
        ),
    ]
