# Generated by Django 3.2.5 on 2022-11-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RazorPayCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='CustomerID')),
                ('cust_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='CustomerName')),
                ('cust_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='CustomerEmail')),
                ('date_created', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='CustomerID')),
                ('virual_account_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Virtual Account ID')),
                ('virual_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
