# Generated by Django 3.2.5 on 2022-02-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_virtualaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualaccount',
            name='cust_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CustomerID'),
        ),
    ]
