# Generated by Django 3.2.5 on 2022-02-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_subscriptions_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_created']},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ['-date_created']},
        ),
    ]
