# Generated by Django 3.2.5 on 2021-12-08 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Meeting ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time of Meeting Creaton')),
                ('service_name', models.CharField(blank=True, max_length=200, verbose_name='Service Name')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
