# Generated by Django 3.2.5 on 2021-12-29 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Meeting ID')),
                ('service_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Service Name')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
