# Generated by Django 3.2.5 on 2022-02-06 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Meeting ID')),
                ('service_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='service_name')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventscheduletime', verbose_name='Meeteing Event')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
