# Generated by Django 3.2.5 on 2022-02-13 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meet', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTypeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_45', models.BooleanField(blank=True, default=False, null=True)),
                ('meet_30', models.BooleanField(blank=True, default=False, null=True)),
                ('meet_60', models.BooleanField(blank=True, default=False, null=True)),
                ('contained_meet', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
    ]
