# Generated by Django 3.2.5 on 2022-02-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventscheduletime_booked'),
        ('meet', '0003_auto_20220203_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='expert',
            new_name='user',
        ),
        migrations.AddField(
            model_name='meeting',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventscheduletime', verbose_name='Meeteing Event'),
        ),
    ]
