# Generated by Django 3.2.5 on 2022-02-05 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220123_1808'),
        ('meet', '0004_auto_20220204_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile', verbose_name='Expert'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.services', verbose_name='Service'),
        ),
    ]
