# Generated by Django 3.2.5 on 2022-02-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0008_remove_meetingrefundcontainer_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='payment_get',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Got Meeting Payment'),
        ),
    ]
