# Generated by Django 3.2.5 on 2022-02-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0010_meeting_refund_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='refunded',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Meeting Refunded'),
        ),
    ]
