# Generated by Django 3.2.5 on 2022-09-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0014_meeting_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtypecount',
            name='meet_30',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meetingtypecount',
            name='meet_45',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meetingtypecount',
            name='meet_60',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
