# Generated by Django 3.2.5 on 2021-12-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplans',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Meeting Duration'),
        ),
        migrations.AlterField(
            model_name='userplans',
            name='no_of_meeting',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='No of Meetings'),
        ),
    ]
