# Generated by Django 3.2.5 on 2021-12-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.JSONField(default=dict, verbose_name='Education'),
        ),
    ]
