# Generated by Django 3.2.5 on 2021-12-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_plans',
            name='no_of_meeting',
            field=models.PositiveBigIntegerField(default=2, verbose_name='No of Meetings'),
        ),
    ]
