# Generated by Django 3.2.5 on 2022-09-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userplans_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refer_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reffered_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
