# Generated by Django 3.2.5 on 2022-10-30 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220909_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='Test Id')),
                ('test_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Test Name')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Title')),
                ('strt_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Test Duration')),
                ('ques_ans_json', models.JSONField(blank=True, default=dict, null=True, verbose_name='Questions')),
                ('sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('test_category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='UserTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualified', models.BooleanField(default=False)),
                ('date_of_test', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_test'],
            },
        ),
    ]
