# Generated by Django 3.2.5 on 2021-12-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_plans_no_of_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('GBP', 'GBP')], default='INR', max_length=10, verbose_name='currency'),
        ),
    ]
