# Generated by Django 3.2.5 on 2022-11-03 16:48

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_test_usertestreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='test',
            old_name='ques_ans_json',
            new_name='options',
        ),
        migrations.RemoveField(
            model_name='test',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='test',
            name='strt_time',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
        migrations.AddField(
            model_name='test',
            name='answers',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='test',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 3, 16, 48, 17, 202746, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='multi_ans',
            field=models.BooleanField(default=False, verbose_name='Multiple Answer'),
        ),
        migrations.AddField(
            model_name='test',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Question'),
        ),
        migrations.AddField(
            model_name='usertestreport',
            name='correct_ans_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number Of Correct Answer'),
        ),
        migrations.AlterField(
            model_name='usertestreport',
            name='date_of_test',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
