# Generated by Django 3.2.5 on 2022-10-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_test_usertestreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='strt_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='test',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertestreport',
            name='date_of_test',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
