# Generated by Django 3.2.5 on 2021-12-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_services_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.JSONField(default=dict, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='services',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('GBP', 'GBP')], default='INR', max_length=10, verbose_name='Currency'),
        ),
    ]
