# Generated by Django 3.2.5 on 2022-10-30 15:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20221030_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='ques_ans_json',
            new_name='options',
        ),
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
        migrations.AddField(
            model_name='test',
            name='answer',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Answer'),
        ),
        migrations.AddField(
            model_name='test',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Question'),
        ),
    ]
