# Generated by Django 3.2.5 on 2022-01-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_comment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Service Type'),
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
