# Generated by Django 3.2.5 on 2022-01-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='ordered',
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
