# Generated by Django 3.2.5 on 2022-02-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='refundstatus',
            options={'ordering': ['-date_created']},
        ),
    ]
